export const ACADEMIC_TITLES = [
  "Dr.",
  "Prof.",
  "Ph.D.",
  "M.D.",
  "D.D.S.",
  "D.V.M.",
  "J.D.",
  "MBA",
  "M.Sc.",
  "M.S.",
  "M.A.",
  "B.Sc.",
  "B.S.",
  "B.A.",
  "B.Eng.",
  "M.Eng.",
  "P.E.",
];

export const CALENDAR_COLORS = [
  { label: "Tomato", value: "#EF4444" },
  { label: "Flamingo", value: "#F97316" },
  { label: "Tangerine", value: "#F59E0B" },
  { label: "Banana", value: "#EAB308" },
  { label: "Sage", value: "#84CC16" },
  { label: "Basil", value: "#22C55E" },
  { label: "Peacock", value: "#06B6D4" },
  { label: "Blueberry", value: "#3B82F6" },
  { label: "Lavender", value: "#8B5CF6" },
  { label: "Grape", value: "#A855F7" },
  { label: "Pink", value: "#EC4899" },
  { label: "Graphite", value: "#6B7280" },
];
