export type FileType =
  "image" | "video" | "document" | "archive" | "audio" | "code" | "other";

export interface FileItem {
  id: string;
  name: string;
  type: FileType;
  size: string;
  sizeBytes: number;
  modifiedAt: string;
  createdAt: string;
  starred: boolean;
  shared: boolean;
  folderId: string | null;
}

export interface Folder {
  id: string;
  name: string;
  color: string;
  filesCount: number;
  size: string;
  parentId: string | null;
}

export const folders: Folder[] = [
  {
    id: "1",
    name: "Design Assets",
    color: "#8B5CF6",
    filesCount: 24,
    size: "1.2 GB",
    parentId: null,
  },
  {
    id: "2",
    name: "Projects",
    color: "#06B6D4",
    filesCount: 18,
    size: "856 MB",
    parentId: null,
  },
  {
    id: "3",
    name: "Documents",
    color: "#F59E0B",
    filesCount: 45,
    size: "234 MB",
    parentId: null,
  },
  {
    id: "4",
    name: "Media",
    color: "#EC4899",
    filesCount: 67,
    size: "4.5 GB",
    parentId: null,
  },
  {
    id: "5",
    name: "Archives",
    color: "#10B981",
    filesCount: 12,
    size: "2.1 GB",
    parentId: null,
  },
];

export const files: FileItem[] = [
  {
    id: "f1",
    name: "Dashboard Mockup.fig",
    type: "image",
    size: "12.4 MB",
    sizeBytes: 13003980,
    modifiedAt: "2 hours ago",
    createdAt: "Dec 15, 2024",
    starred: true,
    shared: true,
    folderId: "1",
  },
  {
    id: "f2",
    name: "Brand Guidelines.pdf",
    type: "document",
    size: "8.2 MB",
    sizeBytes: 8598323,
    modifiedAt: "Yesterday",
    createdAt: "Dec 10, 2024",
    starred: true,
    shared: false,
    folderId: "3",
  },
  {
    id: "f3",
    name: "Product Demo.mp4",
    type: "video",
    size: "248 MB",
    sizeBytes: 260046848,
    modifiedAt: "3 days ago",
    createdAt: "Dec 8, 2024",
    starred: false,
    shared: true,
    folderId: "4",
  },
  {
    id: "f4",
    name: "Client Presentation.pptx",
    type: "document",
    size: "15.7 MB",
    sizeBytes: 16464691,
    modifiedAt: "1 week ago",
    createdAt: "Dec 1, 2024",
    starred: false,
    shared: true,
    folderId: "3",
  },
  {
    id: "f5",
    name: "Source Code.zip",
    type: "archive",
    size: "124 MB",
    sizeBytes: 130023424,
    modifiedAt: "2 weeks ago",
    createdAt: "Nov 25, 2024",
    starred: false,
    shared: false,
    folderId: "5",
  },
  {
    id: "f6",
    name: "UI Components.sketch",
    type: "image",
    size: "34.5 MB",
    sizeBytes: 36175872,
    modifiedAt: "4 days ago",
    createdAt: "Dec 5, 2024",
    starred: true,
    shared: true,
    folderId: "1",
  },
  {
    id: "f7",
    name: "Meeting Notes.docx",
    type: "document",
    size: "256 KB",
    sizeBytes: 262144,
    modifiedAt: "5 hours ago",
    createdAt: "Dec 20, 2024",
    starred: false,
    shared: false,
    folderId: "3",
  },
  {
    id: "f8",
    name: "Background Music.mp3",
    type: "audio",
    size: "4.8 MB",
    sizeBytes: 5033164,
    modifiedAt: "1 month ago",
    createdAt: "Nov 15, 2024",
    starred: false,
    shared: false,
    folderId: "4",
  },
  {
    id: "f9",
    name: "App Icon.png",
    type: "image",
    size: "1.2 MB",
    sizeBytes: 1258291,
    modifiedAt: "6 days ago",
    createdAt: "Dec 3, 2024",
    starred: true,
    shared: true,
    folderId: "1",
  },
  {
    id: "f10",
    name: "Project Backup.tar.gz",
    type: "archive",
    size: "512 MB",
    sizeBytes: 536870912,
    modifiedAt: "2 days ago",
    createdAt: "Dec 18, 2024",
    starred: false,
    shared: false,
    folderId: "5",
  },
  {
    id: "f11",
    name: "Analytics Report.xlsx",
    type: "document",
    size: "2.3 MB",
    sizeBytes: 2411724,
    modifiedAt: "8 hours ago",
    createdAt: "Dec 22, 2024",
    starred: false,
    shared: true,
    folderId: "3",
  },
  {
    id: "f12",
    name: "main.tsx",
    type: "code",
    size: "12 KB",
    sizeBytes: 12288,
    modifiedAt: "1 hour ago",
    createdAt: "Dec 24, 2024",
    starred: false,
    shared: false,
    folderId: "2",
  },
  {
    id: "f13",
    name: "Team Photo.jpg",
    type: "image",
    size: "3.8 MB",
    sizeBytes: 3984588,
    modifiedAt: "3 hours ago",
    createdAt: "Dec 23, 2024",
    starred: false,
    shared: true,
    folderId: "4",
  },
  {
    id: "f14",
    name: "Contract Draft.pdf",
    type: "document",
    size: "1.5 MB",
    sizeBytes: 1572864,
    modifiedAt: "Yesterday",
    createdAt: "Dec 21, 2024",
    starred: true,
    shared: false,
    folderId: "3",
  },
  {
    id: "f15",
    name: "Intro Animation.mov",
    type: "video",
    size: "86 MB",
    sizeBytes: 90177536,
    modifiedAt: "5 days ago",
    createdAt: "Dec 12, 2024",
    starred: false,
    shared: true,
    folderId: "4",
  },
  {
    id: "f16",
    name: "database.sql",
    type: "code",
    size: "45 KB",
    sizeBytes: 46080,
    modifiedAt: "12 hours ago",
    createdAt: "Dec 19, 2024",
    starred: false,
    shared: false,
    folderId: "2",
  },
  {
    id: "f17",
    name: "Podcast Episode.wav",
    type: "audio",
    size: "128 MB",
    sizeBytes: 134217728,
    modifiedAt: "1 week ago",
    createdAt: "Dec 14, 2024",
    starred: true,
    shared: true,
    folderId: "4",
  },
  {
    id: "f18",
    name: "Legacy Data.7z",
    type: "archive",
    size: "256 MB",
    sizeBytes: 268435456,
    modifiedAt: "2 weeks ago",
    createdAt: "Dec 7, 2024",
    starred: false,
    shared: false,
    folderId: "5",
  },
  {
    id: "f19",
    name: "Logo Design.ai",
    type: "image",
    size: "18.2 MB",
    sizeBytes: 19084288,
    modifiedAt: "4 hours ago",
    createdAt: "Dec 22, 2024",
    starred: true,
    shared: true,
    folderId: "1",
  },
  {
    id: "f20",
    name: "Budget 2025.xlsx",
    type: "document",
    size: "890 KB",
    sizeBytes: 911360,
    modifiedAt: "Yesterday",
    createdAt: "Dec 20, 2024",
    starred: false,
    shared: true,
    folderId: "3",
  },
];

export const storageData = {
  used: 8.9,
  total: 15,
  breakdown: [
    { type: "Images", size: 2.4, color: "#8B5CF6" },
    { type: "Videos", size: 3.2, color: "#EC4899" },
    { type: "Documents", size: 1.5, color: "#F59E0B" },
    { type: "Archives", size: 1.2, color: "#10B981" },
    { type: "Other", size: 0.6, color: "#6B7280" },
  ],
};
