// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Mirror Next.js env-loading order so the Prisma CLI sees the same
// DATABASE_URL the app uses at runtime: load `.env` first, then let
// `.env.local` override it (matches Next.js's own precedence).
config({ path: ".env" });
config({ path: ".env.local", override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Prisma 7 reads the seed command from prisma.config.ts, not the legacy
    // package.json `"prisma": { "seed": ... }` key (that convention is a
    // no-op once a prisma.config.ts is present).
    seed: "tsx scripts/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
