export type PayrollStatus = "received" | "pending" | "processed" | "failed";
export type PaymentMethod =
  "Bank Transfer" | "Direct Deposit" | "Wire Transfer";

export interface Payroll {
  id: string;
  payrollId: string;
  totalAmount: number;
  employeeName: string;
  employeeAvatar?: string;
  employeeInitials?: string;
  payPeriod: string;
  paymentMethod: PaymentMethod;
  processedDate: string | null;
  processedTimestamp: number | null;
  status: PayrollStatus;
}

const now = Date.now();
const day = 24 * 60 * 60 * 1000;

export const payrolls: Payroll[] = [
  {
    id: "1",
    payrollId: "PR-202401",
    totalAmount: 120000,
    employeeName: "John Doe",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=john",
    payPeriod: "Feb 1 - Feb 15",
    paymentMethod: "Bank Transfer",
    processedDate: "Today",
    processedTimestamp: now,
    status: "received",
  },
  {
    id: "2",
    payrollId: "PR-202402",
    totalAmount: 115000,
    employeeName: "Jane Smith",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=jane",
    payPeriod: "Jan 16 - Jan 31",
    paymentMethod: "Bank Transfer",
    processedDate: null,
    processedTimestamp: null,
    status: "pending",
  },
  {
    id: "3",
    payrollId: "PR-202403",
    totalAmount: 118500,
    employeeName: "Alex Johnson",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=alex",
    payPeriod: "Jan 1 - Jan 15",
    paymentMethod: "Direct Deposit",
    processedDate: "Yesterday",
    processedTimestamp: now - day,
    status: "processed",
  },
  {
    id: "4",
    payrollId: "PR-202404",
    totalAmount: 110500,
    employeeName: "Emily Davis",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=emily",
    payPeriod: "Dec 16 - Dec 31",
    paymentMethod: "Direct Deposit",
    processedDate: "2 days ago",
    processedTimestamp: now - 2 * day,
    status: "processed",
  },
  {
    id: "5",
    payrollId: "PR-202405",
    totalAmount: 120000,
    employeeName: "Michael Brown",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=michael",
    payPeriod: "Feb 1 - Feb 15",
    paymentMethod: "Bank Transfer",
    processedDate: "3 days ago",
    processedTimestamp: now - 3 * day,
    status: "received",
  },
  {
    id: "6",
    payrollId: "PR-202406",
    totalAmount: 115000,
    employeeName: "Sarah Wilson",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=sarah",
    payPeriod: "Jan 16 - Jan 31",
    paymentMethod: "Wire Transfer",
    processedDate: "4 days ago",
    processedTimestamp: now - 4 * day,
    status: "failed",
  },
  {
    id: "7",
    payrollId: "PR-202407",
    totalAmount: 118500,
    employeeName: "Daniel Lee",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=daniel",
    payPeriod: "Jan 1 - Jan 15",
    paymentMethod: "Wire Transfer",
    processedDate: null,
    processedTimestamp: null,
    status: "pending",
  },
  {
    id: "8",
    payrollId: "PR-202408",
    totalAmount: 110500,
    employeeName: "Olivia Clark",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=olivia",
    payPeriod: "Dec 16 - Dec 31",
    paymentMethod: "Bank Transfer",
    processedDate: "5 days ago",
    processedTimestamp: now - 5 * day,
    status: "received",
  },
  {
    id: "9",
    payrollId: "PR-202409",
    totalAmount: 125000,
    employeeName: "James Miller",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=james",
    payPeriod: "Feb 16 - Feb 28",
    paymentMethod: "Bank Transfer",
    processedDate: "6 days ago",
    processedTimestamp: now - 6 * day,
    status: "received",
  },
  {
    id: "10",
    payrollId: "PR-202410",
    totalAmount: 98500,
    employeeName: "Emma Taylor",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=emma",
    payPeriod: "Mar 1 - Mar 15",
    paymentMethod: "Direct Deposit",
    processedDate: null,
    processedTimestamp: null,
    status: "pending",
  },
  {
    id: "11",
    payrollId: "PR-202411",
    totalAmount: 132000,
    employeeName: "William Anderson",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=william",
    payPeriod: "Mar 16 - Mar 31",
    paymentMethod: "Bank Transfer",
    processedDate: "8 days ago",
    processedTimestamp: now - 8 * day,
    status: "received",
  },
  {
    id: "12",
    payrollId: "PR-202412",
    totalAmount: 89000,
    employeeName: "Sophia Martinez",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=sophia",
    payPeriod: "Apr 1 - Apr 15",
    paymentMethod: "Direct Deposit",
    processedDate: "10 days ago",
    processedTimestamp: now - 10 * day,
    status: "processed",
  },
  {
    id: "13",
    payrollId: "PR-202413",
    totalAmount: 145000,
    employeeName: "Benjamin Garcia",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=benjamin",
    payPeriod: "Apr 16 - Apr 30",
    paymentMethod: "Wire Transfer",
    processedDate: null,
    processedTimestamp: null,
    status: "pending",
  },
  {
    id: "14",
    payrollId: "PR-202414",
    totalAmount: 102500,
    employeeName: "Isabella Rodriguez",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=isabella",
    payPeriod: "May 1 - May 15",
    paymentMethod: "Bank Transfer",
    processedDate: "12 days ago",
    processedTimestamp: now - 12 * day,
    status: "received",
  },
  {
    id: "15",
    payrollId: "PR-202415",
    totalAmount: 97800,
    employeeName: "Ethan Hernandez",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=ethan",
    payPeriod: "May 16 - May 31",
    paymentMethod: "Direct Deposit",
    processedDate: "14 days ago",
    processedTimestamp: now - 14 * day,
    status: "failed",
  },
  {
    id: "16",
    payrollId: "PR-202416",
    totalAmount: 128000,
    employeeName: "Mia Lopez",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=mia",
    payPeriod: "Jun 1 - Jun 15",
    paymentMethod: "Bank Transfer",
    processedDate: "15 days ago",
    processedTimestamp: now - 15 * day,
    status: "processed",
  },
  {
    id: "17",
    payrollId: "PR-202417",
    totalAmount: 135500,
    employeeName: "Alexander Gonzalez",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=alexander",
    payPeriod: "Jun 16 - Jun 30",
    paymentMethod: "Wire Transfer",
    processedDate: "18 days ago",
    processedTimestamp: now - 18 * day,
    status: "received",
  },
  {
    id: "18",
    payrollId: "PR-202418",
    totalAmount: 91200,
    employeeName: "Charlotte Perez",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=charlotte",
    payPeriod: "Jul 1 - Jul 15",
    paymentMethod: "Direct Deposit",
    processedDate: null,
    processedTimestamp: null,
    status: "pending",
  },
  {
    id: "19",
    payrollId: "PR-202419",
    totalAmount: 156000,
    employeeName: "Henry Sanchez",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=henry",
    payPeriod: "Jul 16 - Jul 31",
    paymentMethod: "Bank Transfer",
    processedDate: "20 days ago",
    processedTimestamp: now - 20 * day,
    status: "received",
  },
  {
    id: "20",
    payrollId: "PR-202420",
    totalAmount: 108900,
    employeeName: "Amelia Rivera",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=amelia",
    payPeriod: "Aug 1 - Aug 15",
    paymentMethod: "Direct Deposit",
    processedDate: "22 days ago",
    processedTimestamp: now - 22 * day,
    status: "processed",
  },
  {
    id: "21",
    payrollId: "PR-202421",
    totalAmount: 142300,
    employeeName: "Sebastian Torres",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=sebastian",
    payPeriod: "Aug 16 - Aug 31",
    paymentMethod: "Wire Transfer",
    processedDate: null,
    processedTimestamp: null,
    status: "pending",
  },
  {
    id: "22",
    payrollId: "PR-202422",
    totalAmount: 87500,
    employeeName: "Harper Flores",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=harper",
    payPeriod: "Sep 1 - Sep 15",
    paymentMethod: "Bank Transfer",
    processedDate: "25 days ago",
    processedTimestamp: now - 25 * day,
    status: "received",
  },
  {
    id: "23",
    payrollId: "PR-202423",
    totalAmount: 163000,
    employeeName: "Jack Nguyen",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=jack",
    payPeriod: "Sep 16 - Sep 30",
    paymentMethod: "Direct Deposit",
    processedDate: "28 days ago",
    processedTimestamp: now - 28 * day,
    status: "failed",
  },
  {
    id: "24",
    payrollId: "PR-202424",
    totalAmount: 95400,
    employeeName: "Evelyn Kim",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=evelyn",
    payPeriod: "Oct 1 - Oct 15",
    paymentMethod: "Bank Transfer",
    processedDate: "30 days ago",
    processedTimestamp: now - 30 * day,
    status: "processed",
  },
  {
    id: "25",
    payrollId: "PR-202425",
    totalAmount: 178500,
    employeeName: "Lucas Patel",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=lucas",
    payPeriod: "Oct 16 - Oct 31",
    paymentMethod: "Wire Transfer",
    processedDate: "32 days ago",
    processedTimestamp: now - 32 * day,
    status: "received",
  },
  {
    id: "26",
    payrollId: "PR-202426",
    totalAmount: 104700,
    employeeName: "Aria Chen",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=aria",
    payPeriod: "Nov 1 - Nov 15",
    paymentMethod: "Direct Deposit",
    processedDate: null,
    processedTimestamp: null,
    status: "pending",
  },
  {
    id: "27",
    payrollId: "PR-202427",
    totalAmount: 139200,
    employeeName: "Owen Murphy",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=owen",
    payPeriod: "Nov 16 - Nov 30",
    paymentMethod: "Bank Transfer",
    processedDate: "35 days ago",
    processedTimestamp: now - 35 * day,
    status: "received",
  },
  {
    id: "28",
    payrollId: "PR-202428",
    totalAmount: 82600,
    employeeName: "Lily Cooper",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=lily",
    payPeriod: "Dec 1 - Dec 15",
    paymentMethod: "Direct Deposit",
    processedDate: "38 days ago",
    processedTimestamp: now - 38 * day,
    status: "processed",
  },
  {
    id: "29",
    payrollId: "PR-202429",
    totalAmount: 151800,
    employeeName: "Liam Reed",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=liam",
    payPeriod: "Dec 16 - Dec 31",
    paymentMethod: "Wire Transfer",
    processedDate: "40 days ago",
    processedTimestamp: now - 40 * day,
    status: "received",
  },
  {
    id: "30",
    payrollId: "PR-202430",
    totalAmount: 112300,
    employeeName: "Zoey Bailey",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=zoey",
    payPeriod: "Jan 1 - Jan 15",
    paymentMethod: "Bank Transfer",
    processedDate: null,
    processedTimestamp: null,
    status: "pending",
  },
  {
    id: "31",
    payrollId: "PR-202431",
    totalAmount: 167400,
    employeeName: "Mason Howard",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=mason",
    payPeriod: "Jan 16 - Jan 31",
    paymentMethod: "Direct Deposit",
    processedDate: "42 days ago",
    processedTimestamp: now - 42 * day,
    status: "failed",
  },
  {
    id: "32",
    payrollId: "PR-202432",
    totalAmount: 94100,
    employeeName: "Chloe Ward",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=chloe",
    payPeriod: "Feb 1 - Feb 15",
    paymentMethod: "Bank Transfer",
    processedDate: "Today",
    processedTimestamp: now - 2 * 60 * 60 * 1000,
    status: "processed",
  },
  {
    id: "33",
    payrollId: "PR-202433",
    totalAmount: 183000,
    employeeName: "Noah Cox",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=noah",
    payPeriod: "Feb 16 - Feb 28",
    paymentMethod: "Wire Transfer",
    processedDate: "Yesterday",
    processedTimestamp: now - day - 3 * 60 * 60 * 1000,
    status: "received",
  },
  {
    id: "34",
    payrollId: "PR-202434",
    totalAmount: 101500,
    employeeName: "Ella Diaz",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=ella",
    payPeriod: "Mar 1 - Mar 15",
    paymentMethod: "Direct Deposit",
    processedDate: "3 days ago",
    processedTimestamp: now - 3 * day,
    status: "received",
  },
  {
    id: "35",
    payrollId: "PR-202435",
    totalAmount: 129700,
    employeeName: "Jacob Richardson",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=jacob",
    payPeriod: "Mar 16 - Mar 31",
    paymentMethod: "Bank Transfer",
    processedDate: null,
    processedTimestamp: null,
    status: "pending",
  },
  {
    id: "36",
    payrollId: "PR-202436",
    totalAmount: 88900,
    employeeName: "Grace Wood",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=grace",
    payPeriod: "Apr 1 - Apr 15",
    paymentMethod: "Direct Deposit",
    processedDate: "5 days ago",
    processedTimestamp: now - 5 * day,
    status: "processed",
  },
  {
    id: "37",
    payrollId: "PR-202437",
    totalAmount: 147600,
    employeeName: "Aiden Watson",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=aiden",
    payPeriod: "Apr 16 - Apr 30",
    paymentMethod: "Wire Transfer",
    processedDate: "6 days ago",
    processedTimestamp: now - 6 * day,
    status: "received",
  },
  {
    id: "38",
    payrollId: "PR-202438",
    totalAmount: 106200,
    employeeName: "Victoria Brooks",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=victoria",
    payPeriod: "May 1 - May 15",
    paymentMethod: "Bank Transfer",
    processedDate: "7 days ago",
    processedTimestamp: now - 7 * day,
    status: "failed",
  },
  {
    id: "39",
    payrollId: "PR-202439",
    totalAmount: 171300,
    employeeName: "Logan Gray",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=logan",
    payPeriod: "May 16 - May 31",
    paymentMethod: "Direct Deposit",
    processedDate: "9 days ago",
    processedTimestamp: now - 9 * day,
    status: "received",
  },
  {
    id: "40",
    payrollId: "PR-202440",
    totalAmount: 93800,
    employeeName: "Penelope James",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=penelope",
    payPeriod: "Jun 1 - Jun 15",
    paymentMethod: "Bank Transfer",
    processedDate: null,
    processedTimestamp: null,
    status: "pending",
  },
  {
    id: "41",
    payrollId: "PR-202441",
    totalAmount: 158900,
    employeeName: "Carter Bennett",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=carter",
    payPeriod: "Jun 16 - Jun 30",
    paymentMethod: "Wire Transfer",
    processedDate: "11 days ago",
    processedTimestamp: now - 11 * day,
    status: "processed",
  },
  {
    id: "42",
    payrollId: "PR-202442",
    totalAmount: 85400,
    employeeName: "Layla Price",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=layla",
    payPeriod: "Jul 1 - Jul 15",
    paymentMethod: "Direct Deposit",
    processedDate: "13 days ago",
    processedTimestamp: now - 13 * day,
    status: "received",
  },
  {
    id: "43",
    payrollId: "PR-202443",
    totalAmount: 144500,
    employeeName: "Jackson Ross",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=jackson",
    payPeriod: "Jul 16 - Jul 31",
    paymentMethod: "Bank Transfer",
    processedDate: "16 days ago",
    processedTimestamp: now - 16 * day,
    status: "received",
  },
  {
    id: "44",
    payrollId: "PR-202444",
    totalAmount: 99700,
    employeeName: "Riley Sanders",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=riley",
    payPeriod: "Aug 1 - Aug 15",
    paymentMethod: "Direct Deposit",
    processedDate: null,
    processedTimestamp: null,
    status: "pending",
  },
  {
    id: "45",
    payrollId: "PR-202445",
    totalAmount: 176200,
    employeeName: "Gabriel Perry",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=gabriel",
    payPeriod: "Aug 16 - Aug 31",
    paymentMethod: "Wire Transfer",
    processedDate: "19 days ago",
    processedTimestamp: now - 19 * day,
    status: "failed",
  },
  {
    id: "46",
    payrollId: "PR-202446",
    totalAmount: 107800,
    employeeName: "Nora Powell",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=nora",
    payPeriod: "Sep 1 - Sep 15",
    paymentMethod: "Bank Transfer",
    processedDate: "21 days ago",
    processedTimestamp: now - 21 * day,
    status: "processed",
  },
  {
    id: "47",
    payrollId: "PR-202447",
    totalAmount: 162100,
    employeeName: "Caleb Long",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=caleb",
    payPeriod: "Sep 16 - Sep 30",
    paymentMethod: "Direct Deposit",
    processedDate: "24 days ago",
    processedTimestamp: now - 24 * day,
    status: "received",
  },
  {
    id: "48",
    payrollId: "PR-202448",
    totalAmount: 91600,
    employeeName: "Hannah Patterson",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=hannah",
    payPeriod: "Oct 1 - Oct 15",
    paymentMethod: "Bank Transfer",
    processedDate: "27 days ago",
    processedTimestamp: now - 27 * day,
    status: "received",
  },
  {
    id: "49",
    payrollId: "PR-202449",
    totalAmount: 153400,
    employeeName: "Ryan Hughes",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=ryan",
    payPeriod: "Oct 16 - Oct 31",
    paymentMethod: "Wire Transfer",
    processedDate: null,
    processedTimestamp: null,
    status: "pending",
  },
  {
    id: "50",
    payrollId: "PR-202450",
    totalAmount: 119500,
    employeeName: "Addison Foster",
    employeeAvatar: "https://api.dicebear.com/9.x/glass/svg?seed=addison",
    payPeriod: "Nov 1 - Nov 15",
    paymentMethod: "Direct Deposit",
    processedDate: "29 days ago",
    processedTimestamp: now - 29 * day,
    status: "processed",
  },
];
