export type EmployeeStatus = "active" | "on_leave" | "pending" | "inactive";
export type Department = "IT" | "HR" | "Engineering" | "Marketing" | "Sales";
export type JobTitle =
  | "Software Engineer"
  | "HR Manager"
  | "UX Designer"
  | "Marketing Lead"
  | "Sales Executive"
  | "Product Manager"
  | "Data Analyst"
  | "DevOps Engineer";

export interface Employee {
  id: string;
  empId: string;
  name: string;
  email: string;
  avatar: string;
  department: Department;
  jobTitle: JobTitle;
  joinedDate: string;
  joinedTimestamp: number;
  status: EmployeeStatus;
}

const now = Date.now();
const day = 24 * 60 * 60 * 1000;

export const employees: Employee[] = [
  {
    id: "1",
    empId: "EMP-1001",
    name: "John Doe",
    email: "john.doe@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=johndoe",
    department: "IT",
    jobTitle: "Software Engineer",
    joinedDate: "01 Jan 2025",
    joinedTimestamp: now - 5 * day,
    status: "active",
  },
  {
    id: "2",
    empId: "EMP-1002",
    name: "Jane Smith",
    email: "jane.smith@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=janesmith",
    department: "HR",
    jobTitle: "HR Manager",
    joinedDate: "12 Feb 2025",
    joinedTimestamp: now - 10 * day,
    status: "on_leave",
  },
  {
    id: "3",
    empId: "EMP-1003",
    name: "Alex Johnson",
    email: "alex.johnson@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=alexjohnson",
    department: "Engineering",
    jobTitle: "UX Designer",
    joinedDate: "12 Feb 2025",
    joinedTimestamp: now - 15 * day,
    status: "pending",
  },
  {
    id: "4",
    empId: "EMP-1004",
    name: "Emily Davis",
    email: "emily.davis@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=emilydavis",
    department: "Marketing",
    jobTitle: "Marketing Lead",
    joinedDate: "12 Feb 2025",
    joinedTimestamp: now - 20 * day,
    status: "pending",
  },
  {
    id: "5",
    empId: "EMP-1005",
    name: "Michael Brown",
    email: "michael.brown@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=michaelbrown",
    department: "Sales",
    jobTitle: "Sales Executive",
    joinedDate: "20 Feb 2025",
    joinedTimestamp: now - 25 * day,
    status: "active",
  },
  {
    id: "6",
    empId: "EMP-1006",
    name: "Sarah Wilson",
    email: "sarah.w@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=sarahwilson",
    department: "IT",
    jobTitle: "DevOps Engineer",
    joinedDate: "20 Feb 2025",
    joinedTimestamp: now - 30 * day,
    status: "inactive",
  },
  {
    id: "7",
    empId: "EMP-1007",
    name: "Daniel Lee",
    email: "daniel.l@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=daniellee",
    department: "HR",
    jobTitle: "HR Manager",
    joinedDate: "01 Mar 2025",
    joinedTimestamp: now - 35 * day,
    status: "inactive",
  },
  {
    id: "8",
    empId: "EMP-1008",
    name: "Olivia Clark",
    email: "olivia.c@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=oliviaclark",
    department: "Engineering",
    jobTitle: "Software Engineer",
    joinedDate: "01 Mar 2025",
    joinedTimestamp: now - 40 * day,
    status: "active",
  },
  {
    id: "9",
    empId: "EMP-1009",
    name: "William Turner",
    email: "william.t@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=williamturner",
    department: "Marketing",
    jobTitle: "Marketing Lead",
    joinedDate: "15 Mar 2025",
    joinedTimestamp: now - 45 * day,
    status: "active",
  },
  {
    id: "10",
    empId: "EMP-1010",
    name: "Emma Watson",
    email: "emma.w@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=emmawatson",
    department: "Sales",
    jobTitle: "Sales Executive",
    joinedDate: "15 Mar 2025",
    joinedTimestamp: now - 50 * day,
    status: "on_leave",
  },
  {
    id: "11",
    empId: "EMP-1011",
    name: "James Anderson",
    email: "james.a@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=jamesanderson",
    department: "IT",
    jobTitle: "Data Analyst",
    joinedDate: "01 Apr 2025",
    joinedTimestamp: now - 55 * day,
    status: "active",
  },
  {
    id: "12",
    empId: "EMP-1012",
    name: "Sophia Martinez",
    email: "sophia.m@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=sophiamartinez",
    department: "Engineering",
    jobTitle: "Product Manager",
    joinedDate: "01 Apr 2025",
    joinedTimestamp: now - 60 * day,
    status: "active",
  },
  {
    id: "13",
    empId: "EMP-1013",
    name: "Benjamin Garcia",
    email: "benjamin.g@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=benjamingarcia",
    department: "HR",
    jobTitle: "HR Manager",
    joinedDate: "15 Apr 2025",
    joinedTimestamp: now - 65 * day,
    status: "pending",
  },
  {
    id: "14",
    empId: "EMP-1014",
    name: "Isabella Rodriguez",
    email: "isabella.r@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=isabellarodriguez",
    department: "Marketing",
    jobTitle: "UX Designer",
    joinedDate: "15 Apr 2025",
    joinedTimestamp: now - 70 * day,
    status: "active",
  },
  {
    id: "15",
    empId: "EMP-1015",
    name: "Ethan Hernandez",
    email: "ethan.h@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=ethanhernandez",
    department: "Sales",
    jobTitle: "Sales Executive",
    joinedDate: "01 May 2025",
    joinedTimestamp: now - 75 * day,
    status: "active",
  },
  {
    id: "16",
    empId: "EMP-1016",
    name: "Mia Lopez",
    email: "mia.l@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=mialopez",
    department: "IT",
    jobTitle: "Software Engineer",
    joinedDate: "01 May 2025",
    joinedTimestamp: now - 80 * day,
    status: "active",
  },
  {
    id: "17",
    empId: "EMP-1017",
    name: "Alexander Gonzalez",
    email: "alexander.g@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=alexandergonzalez",
    department: "Engineering",
    jobTitle: "DevOps Engineer",
    joinedDate: "15 May 2025",
    joinedTimestamp: now - 85 * day,
    status: "on_leave",
  },
  {
    id: "18",
    empId: "EMP-1018",
    name: "Charlotte Perez",
    email: "charlotte.p@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=charlotteperez",
    department: "HR",
    jobTitle: "HR Manager",
    joinedDate: "15 May 2025",
    joinedTimestamp: now - 90 * day,
    status: "active",
  },
  {
    id: "19",
    empId: "EMP-1019",
    name: "Henry Sanchez",
    email: "henry.s@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=henrysanchez",
    department: "Marketing",
    jobTitle: "Marketing Lead",
    joinedDate: "01 Jun 2025",
    joinedTimestamp: now - 95 * day,
    status: "active",
  },
  {
    id: "20",
    empId: "EMP-1020",
    name: "Amelia Rivera",
    email: "amelia.r@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=ameliarivera",
    department: "Sales",
    jobTitle: "Sales Executive",
    joinedDate: "01 Jun 2025",
    joinedTimestamp: now - 100 * day,
    status: "inactive",
  },
  {
    id: "21",
    empId: "EMP-1021",
    name: "Sebastian Torres",
    email: "sebastian.t@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=sebastiantorres",
    department: "IT",
    jobTitle: "Data Analyst",
    joinedDate: "15 Jun 2025",
    joinedTimestamp: now - 105 * day,
    status: "active",
  },
  {
    id: "22",
    empId: "EMP-1022",
    name: "Harper Flores",
    email: "harper.f@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=harperflores",
    department: "Engineering",
    jobTitle: "Product Manager",
    joinedDate: "15 Jun 2025",
    joinedTimestamp: now - 110 * day,
    status: "active",
  },
  {
    id: "23",
    empId: "EMP-1023",
    name: "Jack Nguyen",
    email: "jack.n@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=jacknguyen",
    department: "HR",
    jobTitle: "HR Manager",
    joinedDate: "01 Jul 2025",
    joinedTimestamp: now - 115 * day,
    status: "pending",
  },
  {
    id: "24",
    empId: "EMP-1024",
    name: "Evelyn Kim",
    email: "evelyn.k@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=evelynkim",
    department: "Marketing",
    jobTitle: "UX Designer",
    joinedDate: "01 Jul 2025",
    joinedTimestamp: now - 120 * day,
    status: "active",
  },
  {
    id: "25",
    empId: "EMP-1025",
    name: "Lucas Patel",
    email: "lucas.p@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=lucaspatel",
    department: "Sales",
    jobTitle: "Sales Executive",
    joinedDate: "15 Jul 2025",
    joinedTimestamp: now - 125 * day,
    status: "active",
  },
  {
    id: "26",
    empId: "EMP-1026",
    name: "Aria Chen",
    email: "aria.c@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=ariachen",
    department: "IT",
    jobTitle: "Software Engineer",
    joinedDate: "15 Jul 2025",
    joinedTimestamp: now - 130 * day,
    status: "on_leave",
  },
  {
    id: "27",
    empId: "EMP-1027",
    name: "Owen Murphy",
    email: "owen.m@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=owenmurphy",
    department: "Engineering",
    jobTitle: "DevOps Engineer",
    joinedDate: "01 Aug 2025",
    joinedTimestamp: now - 135 * day,
    status: "active",
  },
  {
    id: "28",
    empId: "EMP-1028",
    name: "Lily Cooper",
    email: "lily.c@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=lilycooper",
    department: "HR",
    jobTitle: "HR Manager",
    joinedDate: "01 Aug 2025",
    joinedTimestamp: now - 140 * day,
    status: "active",
  },
  {
    id: "29",
    empId: "EMP-1029",
    name: "Liam Reed",
    email: "liam.r@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=liamreed",
    department: "Marketing",
    jobTitle: "Marketing Lead",
    joinedDate: "15 Aug 2025",
    joinedTimestamp: now - 145 * day,
    status: "active",
  },
  {
    id: "30",
    empId: "EMP-1030",
    name: "Zoey Bailey",
    email: "zoey.b@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=zoeybailey",
    department: "Sales",
    jobTitle: "Sales Executive",
    joinedDate: "15 Aug 2025",
    joinedTimestamp: now - 150 * day,
    status: "pending",
  },
  {
    id: "31",
    empId: "EMP-1031",
    name: "Mason Howard",
    email: "mason.h@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=masonhoward",
    department: "IT",
    jobTitle: "Data Analyst",
    joinedDate: "01 Sep 2025",
    joinedTimestamp: now - 155 * day,
    status: "inactive",
  },
  {
    id: "32",
    empId: "EMP-1032",
    name: "Chloe Ward",
    email: "chloe.w@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=chloeward",
    department: "Engineering",
    jobTitle: "Product Manager",
    joinedDate: "01 Sep 2025",
    joinedTimestamp: now - 160 * day,
    status: "active",
  },
  {
    id: "33",
    empId: "EMP-1033",
    name: "Noah Cox",
    email: "noah.c@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=noahcox",
    department: "HR",
    jobTitle: "HR Manager",
    joinedDate: "15 Sep 2025",
    joinedTimestamp: now - 165 * day,
    status: "active",
  },
  {
    id: "34",
    empId: "EMP-1034",
    name: "Ella Diaz",
    email: "ella.d@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=elladiaz",
    department: "Marketing",
    jobTitle: "UX Designer",
    joinedDate: "15 Sep 2025",
    joinedTimestamp: now - 170 * day,
    status: "active",
  },
  {
    id: "35",
    empId: "EMP-1035",
    name: "Jacob Richardson",
    email: "jacob.r@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=jacobrichardson",
    department: "Sales",
    jobTitle: "Sales Executive",
    joinedDate: "01 Oct 2025",
    joinedTimestamp: now - 175 * day,
    status: "on_leave",
  },
  {
    id: "36",
    empId: "EMP-1036",
    name: "Grace Wood",
    email: "grace.w@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=gracewood",
    department: "IT",
    jobTitle: "Software Engineer",
    joinedDate: "01 Oct 2025",
    joinedTimestamp: now - 180 * day,
    status: "active",
  },
  {
    id: "37",
    empId: "EMP-1037",
    name: "Aiden Watson",
    email: "aiden.w@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=aidenwatson",
    department: "Engineering",
    jobTitle: "DevOps Engineer",
    joinedDate: "15 Oct 2025",
    joinedTimestamp: now - 185 * day,
    status: "active",
  },
  {
    id: "38",
    empId: "EMP-1038",
    name: "Victoria Brooks",
    email: "victoria.b@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=victoriabrooks",
    department: "HR",
    jobTitle: "HR Manager",
    joinedDate: "15 Oct 2025",
    joinedTimestamp: now - 190 * day,
    status: "inactive",
  },
  {
    id: "39",
    empId: "EMP-1039",
    name: "Logan Gray",
    email: "logan.g@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=logangray",
    department: "Marketing",
    jobTitle: "Marketing Lead",
    joinedDate: "01 Nov 2025",
    joinedTimestamp: now - 195 * day,
    status: "active",
  },
  {
    id: "40",
    empId: "EMP-1040",
    name: "Penelope James",
    email: "penelope.j@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=penelopejames",
    department: "Sales",
    jobTitle: "Sales Executive",
    joinedDate: "01 Nov 2025",
    joinedTimestamp: now - 200 * day,
    status: "active",
  },
  {
    id: "41",
    empId: "EMP-1041",
    name: "Carter Bennett",
    email: "carter.b@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=carterbennett",
    department: "IT",
    jobTitle: "Data Analyst",
    joinedDate: "15 Nov 2025",
    joinedTimestamp: now - 205 * day,
    status: "pending",
  },
  {
    id: "42",
    empId: "EMP-1042",
    name: "Layla Price",
    email: "layla.p@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=laylaprice",
    department: "Engineering",
    jobTitle: "Product Manager",
    joinedDate: "15 Nov 2025",
    joinedTimestamp: now - 210 * day,
    status: "active",
  },
  {
    id: "43",
    empId: "EMP-1043",
    name: "Jackson Ross",
    email: "jackson.r@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=jacksonross",
    department: "HR",
    jobTitle: "HR Manager",
    joinedDate: "01 Dec 2025",
    joinedTimestamp: now - 215 * day,
    status: "active",
  },
  {
    id: "44",
    empId: "EMP-1044",
    name: "Riley Sanders",
    email: "riley.s@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=rileysanders",
    department: "Marketing",
    jobTitle: "UX Designer",
    joinedDate: "01 Dec 2025",
    joinedTimestamp: now - 220 * day,
    status: "on_leave",
  },
  {
    id: "45",
    empId: "EMP-1045",
    name: "Gabriel Perry",
    email: "gabriel.p@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=gabrielperry",
    department: "Sales",
    jobTitle: "Sales Executive",
    joinedDate: "15 Dec 2025",
    joinedTimestamp: now - 225 * day,
    status: "active",
  },
  {
    id: "46",
    empId: "EMP-1046",
    name: "Nora Powell",
    email: "nora.p@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=norapowell",
    department: "IT",
    jobTitle: "Software Engineer",
    joinedDate: "15 Dec 2025",
    joinedTimestamp: now - 230 * day,
    status: "active",
  },
  {
    id: "47",
    empId: "EMP-1047",
    name: "Caleb Long",
    email: "caleb.l@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=caleblong",
    department: "Engineering",
    jobTitle: "DevOps Engineer",
    joinedDate: "01 Jan 2024",
    joinedTimestamp: now - 235 * day,
    status: "inactive",
  },
  {
    id: "48",
    empId: "EMP-1048",
    name: "Hannah Patterson",
    email: "hannah.p@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=hannahpatterson",
    department: "HR",
    jobTitle: "HR Manager",
    joinedDate: "01 Jan 2024",
    joinedTimestamp: now - 240 * day,
    status: "active",
  },
  {
    id: "49",
    empId: "EMP-1049",
    name: "Ryan Hughes",
    email: "ryan.h@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=ryanhughes",
    department: "Marketing",
    jobTitle: "Marketing Lead",
    joinedDate: "15 Jan 2024",
    joinedTimestamp: now - 245 * day,
    status: "active",
  },
  {
    id: "50",
    empId: "EMP-1050",
    name: "Addison Foster",
    email: "addison.f@email.com",
    avatar: "https://api.dicebear.com/9.x/glass/svg?seed=addisonfoster",
    department: "Sales",
    jobTitle: "Sales Executive",
    joinedDate: "15 Jan 2024",
    joinedTimestamp: now - 250 * day,
    status: "pending",
  },
];
